version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "18,20,21,22,23,24,30,31,32,33,34,35,40,41,42,43,44,45,50,latest"
    steps:
      - checkout
      # Tox >=4 fails with `ValueError: py310-sphinx{18`
      - run: pip install --user 'tox<4'
      - run: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"

jobs:
  py38:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run-tox:
          version: py38

  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39

  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox:
          version: py310
          # Do not run tests for Python 3.10 and some versions of Sphinx because it's broken
          # See https://github.com/sphinx-doc/sphinx/issues/9816
          sphinx-version: "18,20,21,22,23,24,42,43,44,45,50,latest"

workflows:
  version: 2
  test:
    jobs:
      - py38
      - py39
      - py310

