version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "50,53,60,62,70,73,latest"
    steps:
      - checkout
      # Tox >=4 fails with `ValueError: py310-sphinx{18`
      - run: pip install --user 'tox<4'
      - run: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"

jobs:
  py38:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run-tox:
          version: py38

  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39

  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox:
          version: py310

  py312:
    docker:
      - image: 'cimg/python:3.12'
    steps:
      - run-tox:
          version: py312

workflows:
  version: 2
  test:
    jobs:
      - py38
      - py39
      - py310
      - py312
